### ISSUE TITLE
No Validation on Create

### ISSUE THREAD

**Issue by fishmad** [MattMangoni/nova-blogify-tool#1]
I tried creating a new category without filling in a description and the database caught the error, no validation. Does it need to be mandatory to input a description?
![image](https://user-images.githubusercontent.com/12012101/44649647-d479d200-aa27-11e8-9630-c6bd3508cbc5.png)

**Comment by MattMangoni** [comment]
@fishmad No, it shouldn't be mandatory tbh. I should make the field `nullable`
And even if it was, it would still need some kind of validation.

I'm going to fix it in a few hours :)

**Comment by MattMangoni** [comment]
@fishmad Everything should be fixed in v0.3.0 :)

**Comment by fishmad** [comment]
All good, I downloaded the updated package and just used your admin tool to
remove the two tables than click setup again, fixed it self really easy.
Working good now.
