### ISSUE TITLE
Class 'App\User' Not Found

### ISSUE THREAD

**Issue by PHPJunior** [MattMangoni/nova-blogify-tool#10]
I moved my model to different directory and got this error
<img width="387" alt="screen shot 2018-08-29 at 15 21 12" src="https://user-images.githubusercontent.com/13845077/44776952-52141e00-ab9f-11e8-8b3b-d78ef4271525.png">

**Comment by MattMangoni** [comment]
Yes, I know. Unfortunately, at the moment the package does assume that you have a default file structure. This is less than ideal, but I plan to add a more flexible config-based solution soon :)

**Comment by MattMangoni** [comment]
Feel free to submit a PR if you are going to add that functionalities yourself :)

**Comment by MattMangoni** [comment]
Fix in #22
