### ISSUE TITLE
Can't Type Question Mark in Editor

### ISSUE THREAD

**Issue by developing-sonder** [MattMangoni/nova-blogify-tool#2]
I'm not sure if this is a Mac issue or not, but typing a question mark in the body textarea is a shortcut to jumping to Nova's search feature. This stops the ability to type in a question mark in the body. 

This issue is not present in the Title text field. 

![screen shot 2018-08-28 at 12 50 31 pm](https://user-images.githubusercontent.com/38016259/44740841-0e4ae700-aac1-11e8-830c-daff4ae28880.png)

**Comment by MattMangoni** [comment]
Weird problem. Maybe it has something to do with the Trix field itself? I'm going to investigate as soon as I get back home from work :)

**Comment by developing-sonder** [comment]
Agreed. I've confirmed it on Firefox and Chrome. I plan helping out if I can. I'll look into it tonight as well.

**Comment by MattMangoni** [comment]
Temporarily switch to the Markdown field :)

**Comment by MattMangoni** [comment]
I'm opening a new issue in the laravel/nova-issues repo.
Closing this for now.
