### ISSUE TITLE
Comments title error in search

### ISSUE THREAD

**Issue by eboye** [MattMangoni/nova-blogify-tool#27]
![image](https://user-images.githubusercontent.com/624357/45580983-9a1d8b00-b897-11e8-949e-f44228c2c15d.png)

I've got this error when using global Nova search. I think it's related to this line: https://github.com/MattMangoni/nova-blogify-tool/blob/8d161010cc2b8d50a2dc2afa0121da1d7305f583/src/Resources/Comment.php#L24

where it should not be title but maybe body?

**Comment by MattMangoni** [comment]
Should be solved :)
