### ISSUE TITLE
Change "Nova Blogify Tool" to NovaPress

### ISSUE THREAD

**Issue by dillingham** [MattMangoni/nova-blogify-tool#28]
![71d7020e80f69c9cf352b3e497462b5d904dd8a7 1](https://user-images.githubusercontent.com/29180903/45590549-88280080-b908-11e8-8995-740fbd64da50.jpg)

**Comment by dillingham** [comment]
That’s true, does sound like it would imply certain features and expectations. Just thought a shorten name would do well for adoption and also thought the WordPress implication would attract contributors to help build it out with you. Even nova-blog would work but lacks a little flair :)

**Comment by MattMangoni** [comment]
@dillingham I understand what you're saying, I'll think about it!
If you come up with other names I'm always open to suggestions ;)

**Comment by dillingham** [comment]
### Nova Blog
> In keeping with the original concept

### Nova Posts
> Opens it up to things that function the same but aren't blogs. Bug reports, releases etc

### Nova Publish
> Same as posts, but a little more trendy sounding

### Nova Notebook
> Because who doesn't like alliteration, kinda cheesy and long though
