### ISSUE TITLE
It seems impossible make table structure changes the way migration is setup

### ISSUE THREAD

**Issue by moleculezz** [MattMangoni/nova-blogify-tool#31]
Hi,

I noticed that you are not using the standard way of creating migrations. This limits the possibility to make table structure changes when upgrading to a newer version of your package.
It forces you to destroy the tables and recreate them.
What if you had content which you did not want to destroy?

**Comment by MattMangoni** [comment]
@moleculezz Okay, so, I'm rebuilding everything from scratch.
The result wasn't good enough imho. 

I'll try to keep things simpler and to control each PR closely.
I don't want things to break or to become too complex. 

If you want to contribute, you can find the code (still in early development) inside the "new" repo :)

**Comment by moleculezz** [comment]
@MattMangoni I've been working on something locally. But it drops the entire dashboard that installs the DB tables.
It uses the default `php artisan migration`.

I personally find it easier to let the scripts take care of installing it instead of manually going through the Nova Admin and clicking install. Also I rather not have that for users to see in the Nova Admin.

I didn't want to submit it since I didn't know if you wanted to drop that feature. But I can submit it if you're interested.

**Comment by MattMangoni** [comment]
@moleculezz I don't know, I just didn't want people to have some tables created without even being notified about it :(

**Comment by moleculezz** [comment]
> @moleculezz I don't know, I just didn't want people to have some tables created without even being notified about it :(

This is exactly what Laravel, most Laravel packages and Laravel Nova does for you.

But I understand your point of view. You are looking at it from a CMS user point of view.
In my opinion Laravel Nova was made with the developer in mind. So that's why most things are coded and don't have a UI to click through. It's made for easy deployment.

But hey, it's your package, and that's exactly why I did not submit the PR. I understood you were doing something different.

**Comment by MattMangoni** [comment]
@moleculezz just tweaked stuff a little bit. I didn't understand your point completely

http://prntscr.com/ky5mf0

**Comment by moleculezz** [comment]
That's nice. Instead of executing it from the UI, you just check for the status.
