### ISSUE TITLE
encoding format(tmp) in not supported

### ISSUE THREAD

**Issue by bitkrix** [MattMangoni/nova-blogify-tool#47]
when i want published a post show me this error "encoding format(tmp) in not supported"
i dont know that doing?
my problem just is with upload and storage image

**Comment by MattMangoni** [comment]
I may need some more details to understand the problem better :)
Are you on Windows, maybe?

**Comment by bitkrix** [comment]
yes i working with windown 10
we can speak in whats up this is my phone number +989102680637
